
GET http://localhost:3000/comptes
content-type: application/json

###

POST http://localhost:3000/comptes
content-type: application/json

{
            "id":"3",
            "numero":"NUM_3",
            "montant": 100000,
            "dateCreation":"",
            "transactions":[
                {   
                  "id":"3",
                   "date":"",
                  "montant": 100000,
                  "type":"DEPOT"
                }
            ]
}

###
GET http://localhost:3000/comptes/1
content-type: application/json

###

